# Generated by Django 5.2.10 on 2026-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_ip_address_user_last_ip_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_ip_update',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
