# Generated by Django 5.2.10 on 2026-02-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('users', '0006_remove_user_last_ip_address_and_more'), ('users', '0007_alter_userip_options_remove_userip_updated'), ('users', '0008_alter_userip_unique_together')]

    dependencies = [
        ('users', '0001_squashed_0005_userip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_ip_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_ip_update',
        ),
        migrations.AlterModelOptions(
            name='userip',
            options={'ordering': ['-created'], 'verbose_name_plural': 'User IPs'},
        ),
        migrations.RemoveField(
            model_name='userip',
            name='updated',
        ),
        migrations.AlterUniqueTogether(
            name='userip',
            unique_together=set(),
        ),
    ]
