# Generated by Django 5.2.10 on 2026-02-03 13:09

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title'], 'verbose_name': 'Game', 'verbose_name_plural': 'Gamesss'},
        ),
        migrations.AddField(
            model_name='game',
            name='attachments',
            field=models.FileField(blank=True, help_text='Rules, printable game extras', null=True, upload_to='game_attachments/%Y/%m'),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, help_text='Use markdown'),
        ),
        migrations.AddField(
            model_name='game',
            name='environment',
            field=models.CharField(choices=[('OUT', 'Outdoor'), ('IN', 'Indoor'), ('BOTH', 'Indoor or Outdoor')], default='OUT', help_text='Where is this game best played?', max_length=4),
        ),
        migrations.AddField(
            model_name='game',
            name='equipment',
            field=taggit.managers.TaggableManager(blank=True, help_text='list of equipment (ball, string, paper...)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='game',
            name='max_duration',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='min_duration',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
