# Generated by Django 5.2.10 on 2026-02-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedGame',
            fields=[
            ],
            options={
                'verbose_name': 'Recommended Game',
                'verbose_name_plural': 'Recommended Games',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.game',),
        ),
    ]
