# Generated by Django 5.2.10 on 2026-02-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_recommendedgame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedGame',
        ),
        migrations.CreateModel(
            name='GameWithStats',
            fields=[
            ],
            options={
                'verbose_name': 'Recommended Game',
                'verbose_name_plural': 'Recommended Games',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.game',),
        ),
    ]
