# Generated by Django 5.2.10 on 2026-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_delete_recommendedgame_gamewithstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamewithstats',
            options={'verbose_name': 'Game with stats', 'verbose_name_plural': 'Games with stats'},
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Game can be deactivated without deleting it.'),
        ),
    ]
